---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.6
script: bundle exec rake spec
notifications:
  webhooks: https://hook.bearychat.com/=bwDhF/travis/a286b613c414d3e389a70c9dbec50e97